### PR TITLE
1.2.1

### PR DESCRIPTION
**Pull request by Digenis**
I'll probably rename f0487c258802aabc7fc2f83ba41a8052d169e8ea's cherry-pick commit message
since it's not temporary for 1.2
yet I'm open to discuss adding scrapy-1.6 compatibility in this branch.

Cc: @my8100

### CODE REVIEW

**Comment by my8100** [comment]
@Digenis
Why would you say [f0487c2](https://github.com/scrapy/scrapyd/commit/f0487c258802aabc7fc2f83ba41a8052d169e8ea) is not temporary for 1.2
From my experience, Scrapy 1.2.0 works well with Scrapy 1.6.0

**Comment by my8100** [comment]
And what about the PR #242?

**Comment by Digenis** [comment]
Tests fail for 1.6 because of the eggs. #124 
Since scrapyd-1.2 needs at least scrapy-1.0, I'll rebuild the eggs with 1.0

**Comment by Digenis** [comment]
Added changelog.

I think it's ready to merge and upload to pypi.

**Comment by Digenis** [comment]
2ca36af needs to be cherry-picked to master.
Also, next time I should consider the branching model earlier.

**Comment by Digenis** [comment]
released to github and pypi

**Pull request merged**
