### PR TITLE
PY3 Fix decoding of spider list

### PR DESCRIPTION
**Pull request by redapple**
In Python 3, interpreting output of subprocess call for `scrapyd runner list` (which calls `scrapy list`) as bytes fails JSON encoding tests, spider names being passed as bytes too:

```
UtilsCache.__setitem__(key=mybot, value={'': [b'spider1', b'spider2']})
...
Traceback (most recent call last):
  File "/home/paul/src/scrapyd/scrapyd/tests/test_utils.py", line 66, in test_get_spider_list
    spiders = get_spider_list('mybot', pythonpath=get_pythonpath_scrapyd())
  File "/home/paul/src/scrapyd/scrapyd/utils.py", line 127, in get_spider_list
    get_spider_list.cache[project] = project_cache
  File "/home/paul/src/scrapyd/scrapyd/utils.py", line 52, in __setitem__
    self.cache_manager[key] = value
  File "/home/paul/src/scrapyd/scrapyd/sqlite.py", line 38, in __setitem__
    key, value = self.encode(key), self.encode(value)
  File "/home/paul/src/scrapyd/scrapyd/sqlite.py", line 97, in encode
    return sqlite3.Binary(to_bytes(json.dumps(obj)))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
builtins.TypeError: b'spider1' is not JSON serializable

scrapyd.tests.test_utils.GetSpiderListTest.test_get_spider_list
```

This PR forces the [subprocess output](https://github.com/scrapy/scrapyd/blob/master/scrapyd/utils.py#L112) environement IO encoding to UTF-8 (using [`PYTHONIOENCODING`](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONIOENCODING) in order to work with Unicode spider names.
This is needed for Python 2, otherwise, ASCII is used by the subprocess.

### CODE REVIEW

**Comment by Digenis** [comment]
No, I think it must be ascii by default.
We need a test with a spider name that can't be encoded in ascii.

**Comment by redapple** [comment]
Oddly enough, the new `test_get_spider_list_unicode` test passes on Python 3, with `Popen.communicate()` `out` and `err` being:

```
b'ara\xc3\xb1a1\nara\xc3\xb1a2\n'
b'/home/paul/src/scrapyd/.tox/py35/lib/python3.5/site-packages/scrapy/settings/deprecated.py:26: ScrapyDeprecationWarning: You are using the following settings which are deprecated or obsolete (ask scrapy-users@googlegroups.com for alternatives):\n    BOT_VERSION: no longer used (user agent defaults to Scrapy now)\n  warnings.warn(msg, ScrapyDeprecationWarning)\n/tmp/mybot-r1-mk6v6cdl.egg/mybot/spiders/spider1.py:2: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead\n/tmp/mybot-r1-mk6v6cdl.egg/mybot/spiders/spider1.py:4: ScrapyDeprecationWarning: mybot.spiders.spider1.Spider1 inherits from deprecated class scrapy.spiders.BaseSpider, please inherit from scrapy.spiders.Spider. (warning only on first subclass, there may be others)\n'
```

But fails in Python 2, with `err`

```
/home/paul/src/scrapyd/.tox/py27/local/lib/python2.7/site-packages/scrapy/settings/deprecated.py:26: ScrapyDeprecationWarning: You are using the following settings which are deprecated or obsolete (ask scrapy-users@googlegroups.com for alternatives):
    BOT_VERSION: no longer used (user agent defaults to Scrapy now)
  warnings.warn(msg, ScrapyDeprecationWarning)
/tmp/mybot-r1-FFNofl.egg/mybot/spiders/spider1.py:2: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
/tmp/mybot-r1-FFNofl.egg/mybot/spiders/spider1.py:4: ScrapyDeprecationWarning: mybot.spiders.spider1.Spider1 inherits from deprecated class scrapy.spiders.BaseSpider, please inherit from scrapy.spiders.Spider. (warning only on first subclass, there may be others)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/paul/src/scrapyd/scrapyd/runner.py", line 40, in <module>
    main()
  File "/home/paul/src/scrapyd/scrapyd/runner.py", line 37, in main
    execute()
  File "/home/paul/src/scrapyd/.tox/py27/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/paul/src/scrapyd/.tox/py27/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/home/paul/src/scrapyd/.tox/py27/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/home/paul/src/scrapyd/.tox/py27/local/lib/python2.7/site-packages/scrapy/commands/list.py", line 14, in run
    print(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 3: ordinal not in range(128)
```

**Comment by redapple** [comment]
hm, nevermind, Python 3 test fails too (for another reason)

**Comment by redapple** [comment]
@Digenis , do you think setting `PYTHONIOENCODING` for the subprocess env is reasonable?

**Comment by Digenis** [comment]
Unfortunately python is poor in this matter.
There's no other way for python processes to agree on the encoding of streams.

**Comment by redapple** [comment]
@Digenis , are you ok with merging this?
Is the "bug" tag to remember to backport it?

**Comment by Digenis** [comment]
> Is the "bug" tag to remember to backport it?

Exactly

> @Digenis , are you ok with merging this?

Is e2226b6 something temporary to be deleted in a rebase?

**Comment by redapple** [comment]
I can squash

**Comment by Digenis** [comment]
Seems ok to me.
The coverage report failure in the build
can probably be attributed to the rebase.

**Comment by redapple** [comment]
I think the coverage report failure are due to coverage==4.2 (on Travis)
My local virtualenv has 4.1 and works.
I'll try a few things

**Comment by Digenis** [comment]
I thought it was working a few commit ago.

**Comment by redapple** [comment]
hm, well yeah, coverage==4.2 works locally for me

**Pull request merged**
