### PR TITLE
Add configurable egg storage

### PR DESCRIPTION
**Pull request by mxdev88**
This implements #393. Can someone pls review?

### CODE REVIEW

**Comment by Digenis** [comment]
The same can be said for the queue storage
but I see you already commented on #201.

What exactly are you replacing the egg storage with?
Do you copy the eggs from some external storage
to your heroku image on `IEggStorage.__init__`
and back again everytime `IEggStorage.put` is called?

Although I'm reluctant to add new features
this is just moving code around
so that a config option can be used.
I'll merge.

I'm waiting for a comment on #398, which fixes the CI.
After fixing it, I'll remind you to rebase on master to get a green light from the CI.

**Comment by mxdev88** [comment]
> The same can be said for the queue storage
> but I see you already commented on #201.

Agreed. That gives user full control which is quite nice.

> What exactly are you replacing the egg storage with?

Use PL/SQL database. The egg is stored as Large Binary object.

> Do you copy the eggs from some external storage
> to your heroku image on `IEggStorage.__init__`
> and back again everytime `IEggStorage.put` is called?

Yes, `IEggStorage.put` saves the egg in the database and `IEggStorage.get` retrieves it back.

**Comment by Digenis** [comment]
> and `IEggStorage.get` retrieves it back.

Isn't this is as slow as using a fuse mountpoint?
I thought you'd copy them on init,
to prevent roundtrips on every read.

Are you deploying by inserting eggs in a database
instead of posting them to addversion?

That's a different use case from what I imagined
but I still don't mind merging this.

**Comment by Digenis** [comment]
@mxdev88 you can now rebase on master.
Also, add a line in the changelog at docs/news.rst, section 1.3.0/Added
`- Configuration option for egg storage class`

**Comment by Digenis** [comment]
@mxdev88 this one will get merged sooner.

Just rebase (not merge) on upstream master before you add the changelog line

**Comment by mxdev88** [comment]
@Digenis done if you want to take a look. thanks

**Review by jpmckinney — APPROVED** [review]

**Comment by pawelmhm** [comment]
@mxdev88 can you merge recent master here as well. It would be also good to add some basic unit test for this functionality and we can release it with 1.3

**Comment by pawelmhm** [comment]
integrated with master branch here: https://github.com/scrapy/scrapyd/pull/419/files I'll add test and merge

**Comment by pawelmhm** [comment]
added test and merged here: https://github.com/scrapy/scrapyd/pull/419 will go to 1.3

**Pull request closed without merging**
