### PR TITLE
Dynamic requirements for different pythons

### PR DESCRIPTION
**Pull request by Digenis**
Also, it would be interesting to see if just backporting #62 can make it compatible with 1.0.

### CODE REVIEW

**Comment by Digenis** [comment]
Also, it would be interesting to see if just backporting #62 can make it compatible with 1.0.

**Comment by Digenis** [comment]
It looks like python2.6 support needs to be dropped to use scrapy-0.24.
Should python2.6 support be dropped on a bugfix version? I think not.
However I'd still consider backporting #62.

**Comment by Digenis** [comment]
I need a comment from the developers on this.
scrapyd-1.0 still supports py2.6 so the only way to set version dependencies properly
is to restrict its scrapy version to 0.18.
Otherwise py2.6 support will be dropped on a bugfix release.

The only workaround I can think of is using version_info in setup.py to decide scrapy's max version.
Does this sound sane?

**Comment by Digenis** [comment]
This PR is ready.
Anyone willing to review it?

**Comment by redapple** [comment]
@Digenis , I'm not sure I follow (excuse my very poor knowledge of scrapyd)

I don't understand your sentences:
"Should python2.6 support be dropped on a bugfix version? I think not.
 "Otherwise py2.6 support will be dropped on a bugfix release."

My preference would be to drop Python 2.6 support in the next minor or major release of scrapyd.
[Scrapy dropped Py2.6 support nearly 2.5 years ago](https://github.com/scrapy/scrapy/blob/master/docs/news.rst#0200-released-2013-11-08)

Python 3 support is also needed and too many Pythons is already a lot of effort for scrapy itself.

**Comment by Digenis** [comment]
I replaced the last commit, the new one properly disables wheel building.
I do this because the scrapy and twisted version requirements depend on the python version
(as seen in 63ff12f1e103f9830df1fd6d4820386f2bf22eaf)

The reason I add a bugfix on this branch is because of users who ended up depending on some scrapyd-1.0 behavior.

I definitely want to bump a new release on which python2.6 support is dropped 
so that development can go on. I hope this is the last bugfix bump on 1.0.

My question to scraping hub is whether its apt repositories will get updated with this
otherwise I should drop them from the documentation.

**Comment by redapple** [comment]
@Digenis , sorry it's taking so long about the apt repos.
It looks like we'll have resources to work on our repos/PPA/bintray offering soon.

**Comment by Digenis** [comment]
Fixed the w3lib dependency and squashed.
I'll wait for comments a few days and merge.

**Pull request merged**
