### PR TITLE
auto pip install requires.(install_requires of setup.py)

### PR DESCRIPTION
**Pull request by cleocn**
https://github.com/scrapy/scrapyd/issues/246

when scrapyd-deploy ,can auto call pip install .

### CODE REVIEW

**Comment by Digenis** [comment]
Hi @cleocn,
Thank you for your contribution.
Unfortunately, this is not the way we want to fix it.
There should be some separation between projects' environments.
I think scrapyd is not ready for such a change.

**Comment by cleocn** [comment]
agree to you. maybe something like pyenv/virtualenv it's a good choice.
and thank you for the great scrapyd.

but it can save a lot of time for me .
because i run  scrapyd in docker.
installed packages will lost when i restart the docker container.

**Comment by GrazianoFracasso** [comment]
Hi all, i run scrapyd on docker, I already read that you don't want to resolve this way, but I forked cleocn:master in order to resolve pip main error. ( https://stackoverflow.com/questions/49839610/attributeerror-module-pip-has-no-attribute-main/49990889 pip main is not supported in latest versions ).
[https://github.com/GrazianoFracasso/scrapyd/commit/a4d83aa1ed6fcdf8c86610c5c8656b44f55a156f](a4d83aa1ed6fcdf8c86610c5c8656b44f55a156f)

**Comment by georgescumihai** [comment]
Ok, so what is the workaround to install requirements ?

**Comment by jpmckinney** [comment]
Closing per above comment by maintainer. Related: #224 and https://github.com/scrapy/scrapyd-client/issues/79

**Pull request closed without merging**
