### PR TITLE
Forgotten job placeholder in the 'logs_filename' setting

### PR DESCRIPTION
**Pull request by decaz**
Added job placeholder {job} into the 'logs_filename' setting.

### CODE REVIEW

**Comment by Digenis** [comment]
Looks good to me.
I'd squash if I were you.

**Comment by Digenis** [comment]
@decaz, can you squash?

**Comment by decaz** [comment]
I have already removed fork.. But I can create a new PR with a single commit - is it OK?

**Comment by Digenis** [comment]
Well my opinion is that we should revert the whole logs_filename feature
in favour of some scrapyd.contrib webservice that does the formatting
because it's too much for environ.py to be occupied with this kind of things.
In this case there's no point in starting over.

**Comment by decaz** [comment]
I agree, though this PR can be merged because it's simply a feature, which subsequently can be taken into account during refactoring you talking about.

**Comment by Digenis** [comment]
Squashed and merged in da66373c8f871dc40fae97174930e94c4aa5670b.

**Pull request closed without merging**
