### PR TITLE
Fix poller test by handling polling order uncertainty for 2 projects

### PR DESCRIPTION
**Pull request by redapple**
Project queues container in `poller.py` does not guarantee project order [when iterating on them project keys](https://github.com/scrapy/scrapyd/blob/98da8bc41c37bb971eda0a2223ada543e81ba6a8/scrapyd/poller.py#L20) ([it's a `dict`](https://github.com/scrapy/scrapyd/blob/48c7f8d16b202329dae446f381c4552adbde886f/scrapyd/utils.py#L58))

So in `test_poll_next`, polling results can be:
* either project1/spider1 then project2/spider2,
* or project2/spider2 then project1/spider1

This aims to fix (recently noticed) instability with `scrapyd/tests/test_poller.py` (e.g. https://travis-ci.org/scrapy/scrapyd/jobs/148934915, also see https://github.com/scrapy/scrapyd/pull/162)
```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/travis/build/scrapy/scrapyd/scrapyd/tests/test_poller.py", line 40, in test_poll_next
    self.failUnlessEqual(d1.result, {'_project': 'mybot1', '_spider': 'spider1'})
  File "/home/travis/build/scrapy/scrapyd/.tox/py27/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 835, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: {'_spider': u'spider2', '_project': 'mybot2'} != {'_spider': 'spider1', '_project': 'mybot1'}
- {'_project': 'mybot2', '_spider': u'spider2'}
?                    ^              -       ^
+ {'_project': 'mybot1', '_spider': 'spider1'}
?                    ^                     ^
scrapyd.tests.test_poller.QueuePollerTest.test_poll_next
```

### CODE REVIEW

**Comment by redapple** [comment]
@Digenis , are you ok with this change?

**Comment by Digenis** [comment]
So the error was in the test?
It looks like I misunderstood the whole bug.
Is this relevant at all to the 3 duplicate tickets I listed?

**Comment by redapple** [comment]
As far as I understand, yes, the test assumes `project1/spider1` will get to run first, then `project2/spider2`.
But the implementation does not guarantee this.
Either the guarantee needs to be added (with sorted project list and ordered dict for the spider queues (which I also tested locally), or the test needs to handle one order or the other (this PR)

**Comment by redapple** [comment]
@Digenis , no, I don't think this is related to https://github.com/scrapy/scrapyd/pull/162#issuecomment-234728259

**Comment by Digenis** [comment]
I see.
Let's have it merged.

**Pull request merged**
