### PR TITLE
Add 'Schedule' buttons in the Jobs page

### PR DESCRIPTION
**Pull request by my8100**
This PR adds a schedule endpoint based on #256.
Note that the 'Cancel' and the 'Schedule' buttons still not visible
in Python 3 due to #312.

### CODE REVIEW

**Comment by my8100** [comment]
@Digenis, What do you think about the added 'Schedule' button?

**Comment by Digenis** [comment]
There's no way to add arguments and settings
and, taken from the finished jobs,
it creates the confusion that the job will run with the same arguments.

The reason I wrote the cancel shortcut is that the solution suits any user.

If we add a form to add arguments, we are getting in to the scope of other tools
such as scrapyweb.

**Comment by my8100** [comment]
Not every spider run needs arguments and settings from cmd.
And it's convenient for repeating crawling jobs with just a click.

PS: typo for *scrapydweb*

**Comment by jpmckinney** [comment]
I share the concerns of @Digenis in https://github.com/scrapy/scrapyd/pull/321#issuecomment-485448325

**Pull request closed without merging**
