### PR TITLE
Lower scrapy 1.1 dependency to 1.0

### PR DESCRIPTION
**Pull request by Digenis**
An attempt for https://github.com/scrapy/scrapyd/pull/179#issuecomment-243439640

It's hard to verify the return types of all these functions for both pythons
so I did the easy parts in `sqlite.py` and replaced `to_native_str()` in `native_stringify_dict()`

### CODE REVIEW

**Comment by Digenis** [comment]
Do we have to note anything about scrapy and the license?

**Comment by redapple** [comment]
How do you mean?

**Comment by Digenis** [comment]
The code, though modified, was copied from scrapy.

**Comment by redapple** [comment]
I think it's just fine

**Pull request merged**
