### PR TITLE
make poller test show both results in 1st failure

### PR DESCRIPTION
**Pull request by Digenis**
To help investigate random failures like https://travis-ci.org/scrapy/scrapyd/jobs/146643562
@redapple

### CODE REVIEW

**Comment by redapple** [comment]
This new test sometimes fails for me with
```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/paul/src/scrapyd/scrapyd/tests/test_poller.py", line 40, in test_poll_next
    self.failUnlessEqual([d1.result, d2.result],
exceptions.AttributeError: Deferred instance has no attribute 'result'

scrapyd.tests.test_poller.QueuePollerTest.test_poll_next
-------------------------------------------------------------------------------
```
(same frequency as the random failures mentioned above)

This is what `d1` and `d2` look like before the `failUnlessEqual`

```
d1: __dict__={'callbacks': [], 'called': True, '_canceller': <bound method DeferredQueue._cancelGet of <twisted.internet.defer.DeferredQueue object at 0x7f1f9507b8d0>>, '_chainedTo': None, 'result': {'_project': 'mybot2', '_spider': u'spider2'}}, .paused=0, .called=True
d2: __dict__={'callbacks': [], '_canceller': <bound method DeferredQueue._cancelGet of <twisted.internet.defer.DeferredQueue object at 0x7f1f9507b8d0>>}, .paused=0, .called=False
```
ie. no `result` for `d2`

**Comment by Digenis** [comment]
Which means that what was supposed to be d1, goes missing.
This is for someone more familiar with twisted than I am.

**Comment by Digenis** [comment]
Maybe scrapy/scrapy#28, #6 and #40 are relevant.
@shaneaevans and @aspidites seemed to have a clue on what causes it.

**Comment by Digenis** [comment]
Closing because it doesn't solve a problem.
Continued in #40

**Pull request closed without merging**
