### PR TITLE
Use setup.py and setup.cfg instead of other files

### PR DESCRIPTION
**Pull request by jpmckinney**
- build: Describe requirements in setup.py exclusively
- test: Move .coveragerc into setup.cfg
- ci: Publish to TestPyPI on push

### CODE REVIEW

**Comment by jpmckinney** [comment]
@Gallaecio @pablohoffman Are you able to set the `TEST_PYPI_TOKEN` secret on this repository? Same as was done for scrapyd-client: https://github.com/scrapy/scrapyd-client/pull/87#issuecomment-925474485

I'll merge this PR without the TestPyPI integration for now.

**Comment by Gallaecio** [comment]
> Are you able to set the `TEST_PYPI_TOKEN` secret on this repository?

Done!

**Comment by jpmckinney** [comment]
@Gallaecio Hmm, #446 is failing:

> HTTPError: 403 Forbidden from https://test.pypi.org/legacy/            
> [26](https://github.com/scrapy/scrapyd/runs/6528141059?check_suite_focus=true#step:7:27)
>         The user 'scrapy' isn't allowed to upload to project 'scrapyd'.

Does the user scrapy have an account at test.pypi.org? It's independent from www.pypi.org.

**Comment by Gallaecio** [comment]
Oh, https://test.pypi.org/project/scrapyd/ exists already and does not seem to have scrapy as a maintainer. I did not bother to check. @curita Could you add `scrapy` as a co-maintainer to the `scrapyd` on the testing PyPI service?

**Comment by curita** [comment]
@Gallaecio done! I added `scrapy` as owner of the project.
@jpmckinney I believe the build should work now!

**Comment by jpmckinney** [comment]
It works! Thank you 🎉

**Comment by jpmckinney** [comment]
@Gallaecio @curita The workflow is giving the following error. Can you set up 2FA on the scrapy PyPI user? You will need to do this on both test.pypi.org and pypi.org

> ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
>          User 'scrapy' does not have two-factor authentication enabled. Please  
>          enable two-factor authentication before attempting to upload to PyPI.  
>          See https://test.pypi.org/help/#two-factor-authentication for more     
>          information.

**Comment by Gallaecio** [comment]
I believe it is already set up in pypi.org, but I’ll try to get it done in test.pypi.org

**Comment by Gallaecio** [comment]
Sorry for the delay, this should now be working in test.pypi.org as well.

**Comment by jpmckinney** [comment]
Thank you!

**Pull request merged**
