### PR TITLE
Show job priority in Jobs page and listjobs.json

### PR DESCRIPTION
**Pull request by my8100**
This PR is created as schedule.json accepts parameter `priority` in PR #161.

### CODE REVIEW

**Comment by my8100** [comment]
## The Jobs page
image
image
image

## Output of listjobs.json
```
{'node_name': 'hostname',
 'status': 'ok',
 'pending': [{'project': 'TESTING2',
   'spider': 'test',
   'id': '-1',
   'priority': -1.0},
  {'project': 'TESTING2', 'spider': 'test', 'id': '-2', 'priority': -2.0}],
 'running': [{'project': 'TESTING',
   'spider': 'test',
   'id': '-2',
   'priority': -2.0,
   'pid': 115780,
   'start_time': '2019-06-24 18:34:51.158649'},
  {'project': 'TESTING2',
   'spider': 'test',
   'id': '2',
   'priority': 2.0,
   'pid': 26548,
   'start_time': '2019-06-24 18:34:56.168935'},
  {'project': 'TESTING2',
   'spider': 'test',
   'id': '1',
   'priority': 1.0,
   'pid': 18600,
   'start_time': '2019-06-24 18:35:01.951266'},
  {'project': 'TESTING2',
   'spider': 'test',
   'id': '0',
   'priority': 0.0,
   'pid': 38252,
   'start_time': '2019-06-24 18:35:06.158507'}],
 'finished': [{'project': 'TESTING',
   'spider': 'test',
   'id': '1',
   'priority': 1.0,
   'start_time': '2019-06-24 18:32:41.167214',
   'end_time': '2019-06-24 18:34:49.547557'},
  {'project': 'TESTING',
   'spider': 'test',
   'id': '2',
   'priority': 2.0,
   'start_time': '2019-06-24 18:32:46.197501',
   'end_time': '2019-06-24 18:34:54.385833'},
  {'project': 'TESTING',
   'spider': 'test',
   'id': '0',
   'priority': 0.0,
   'start_time': '2019-06-24 18:32:51.171786',
   'end_time': '2019-06-24 18:34:59.517127'},
  {'project': 'TESTING',
   'spider': 'test',
   'id': '-1',
   'priority': -1.0,
   'start_time': '2019-06-24 18:32:56.163071',
   'end_time': '2019-06-24 18:35:05.510470'}]}
```

**Comment by my8100** [comment]
I would update the test cases ASAP.

**Comment by Digenis** [comment]
It seems that there's no backward compatible way to include it anywhere at all.

**Comment by my8100** [comment]
What to backward compatible?

**Comment by Digenis** [comment]
Anyone using a custom laucher, poller, spiderqueue, sqlitequeue will have their code broken.
It's been long since the last release. Let's make the transition smooth.
Let's release 1.3 without it and include it in 1.4

**Comment by my8100** [comment]
Any plan on the release of 1.3?
When and what new features (but not implemented yet) to be included?

**Comment by Digenis** [comment]
https://github.com/scrapy/scrapyd/milestone/4

**Comment by my8100** [comment]
Add this to the 1.4.0 milestone?

**Comment by jpmckinney** [comment]
Can do along with #272, so closing here as there are conflicts and we'd need to make new commits either way.

**Comment by jpmckinney** [comment]
To add some detail to this comment:

> Anyone using a custom laucher, poller, spiderqueue, sqlitequeue will have their code broken.

This PR would require changing these interfaces:

* `ISpiderQueue.list` to return a list of (msg, priority) tuples instead of a list of msg.
* `ISpiderQueue.pop` to return a (msg, priority) tuple instead of a msg.
* `IPoller.next` to return a dict with a `_priority` key.

**Comment by jpmckinney** [comment]
Can maybe consider these changes as part of a major version update like #187

**Pull request closed without merging**
