### PR TITLE
Update deploy.rst

### PR DESCRIPTION
**Pull request by ewokcillo**
I think scrapyd-deploy search ~/scrapy.cfg not ~/.scrapy.cfg

### CODE REVIEW

**Comment by wvengen** [comment]
Doing an `strace` on scrapyd 0.17 I see that `scrapy.cfg` is searched for in the current directory and all its parents.

**Comment by ewokcillo** [comment]
Sorry, I'm using an old version from ubuntu repository!!!

**Comment by wvengen** [comment]
Scrapy has its own repository at for more recent versions. Add to your `/etc/apt/sources.list`:

```
deb http://archive.scrapy.org/ubuntu scrapy main
```

I guess this issue can be closed now.

**Comment by ewokcillo** [comment]
Thanks!!!

**Pull request closed without merging**
