### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by Digenis**
1.1 is supported but left with bugs for quite some time.
There are bugs already fixed in master
that could make for a bugfix release.

I'm open for suggestions for bugfixes not merged into 1.1
or confirmed bugs that can be fixed in a backwards compatible way.
- [x] Fix overriden FEED_URI
- [x] Missing documentation fixes
- [x] Update sphinx-doc conf
- [x] Enable python2.6 testing (shipped supporting it)

Work in progress:
- [x] sqlite dict and queues fixes
- [x] add changelog
- [x] Dependencies: does it work with scrapy-1.1 despite the deprecations?

### CODE REVIEW

**Comment by Digenis** [comment]
I should also test scrapyd-1.1 with the new scrapy to adjust the dependencies or add a patch.

**Comment by redapple** [comment]
Regarding
> ~~396421a~~→ why/where from did I cherry-pick this?

I'm not sure if the question still holds, but it's originally from https://github.com/scrapy/scrapyd/pull/113/commits/b2a84a0008c68bdcbcbe7c598ce7ea8990c4f6fb from #113

**Comment by Digenis** [comment]
Right! Here, the commits are displayed in chronological order
and since I added them long after the ones in #67
some irrelevant commits of mine got betweens jurov's and my addition to his PR.
Thanks.

**Comment by Digenis** [comment]
Fixed the travis py26 failure.

**Comment by Digenis** [comment]
I'm done with this ticket.
I think we can release 1.1.1.

I'll merge this into the 1.1 branch,
then I'll merge #152 into 1.1
add a release date and bump 1.1.1.

Comments?

**Comment by Digenis** [comment]
For the record, it has some deprecation warnings for scrapy-1.1
but let's leave these for scrapyd-1.2
because it will take some hacks to silence them in a backward compatible way.

**Comment by redapple** [comment]
@Digenis , looks good to me.

**Comment by Digenis** [comment]
I deployed 1.1.1 on my server without problems.
Tomorrow I'll make a release.

**Comment by Digenis** [comment]
@redapple, will you make this available in pypi?

**Comment by redapple** [comment]
@Digenis , done.

**Pull request merged**
