### PR TITLE
[runner.py] don't call get_application

### LINKED ISSUE #377: Scrapyd does not support spiders that use AsyncioSelectorReactor
Currently scrapyd does not support spiders that use asyncio coroutines. When you upload the spider to scrapyd it fails with the following error. I didn't see a way to override the twisted reactor implementation in scrapyd. 

```
scrapyd_1        | 2020-05-16T13:56:19+0000 [_GenericHTTPChannelProtocol,0,172.18.0.1] Unhandled Error
scrapyd_1        | 	Traceback (most recent call last):
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/twisted/web/http.py", line 2284, in allContentReceived
scrapyd_1        | 	    req.requestReceived(command, path, version)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/twisted/web/http.py", line 946, in requestReceived
scrapyd_1        | 	    self.process()
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/twisted/web/server.py", line 235, in process
scrapyd_1        | 	    self.render(resrc)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/twisted/web/server.py", line 302, in render
scrapyd_1        | 	    body = resrc.render(self)
scrapyd_1        | 	--- <exception caught here> ---
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/webservice.py", line 21, in render
scrapyd_1        | 	    return JsonResource.render(self, txrequest).encode('utf-8')
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/utils.py", line 20, in render
scrapyd_1        | 	    r = resource.Resource.render(self, txrequest)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/twisted/web/resource.py", line 265, in render
scrapyd_1        | 	    return m(request)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/webservice.py", line 88, in render_POST
scrapyd_1        | 	    spiders = get_spider_list(project, version=version)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/utils.py", line 134, in get_spider_list
scrapyd_1        | 	    raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
scrapyd_1        | 	builtins.RuntimeError: /usr/local/lib/python3.6/dist-packages/scrapy/utils/project.py:94: ScrapyDeprecationWarning: Use of environment variables prefixed with SCRAPY_ to override settings is deprecated. The following environment variables are currently defined: EGG_VERSION
scrapyd_1        | 	  ScrapyDeprecationWarning
scrapyd_1        | 	Traceback (most recent call last):
scrapyd_1        | 	  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
scrapyd_1        | 	    "__main__", mod_spec)
scrapyd_1        | 	  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
scrapyd_1        | 	    exec(code, run_globals)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/runner.py", line 40, in <module>
scrapyd_1        | 	    main()
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapyd/runner.py", line 37, in main
scrapyd_1        | 	    execute()
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 144, in execute
scrapyd_1        | 	    cmd.crawler_process = CrawlerProcess(settings)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 265, in __init__
scrapyd_1        | 	    super(CrawlerProcess, self).__init__(settings)
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 141, in __init__
scrapyd_1        | 	    self._handle_twisted_reactor()
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 329, in _handle_twisted_reactor
scrapyd_1        | 	    super()._handle_twisted_reactor()
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 237, in _handle_twisted_reactor
scrapyd_1        | 	    verify_installed_reactor(self.settings["TWISTED_REACTOR"])
scrapyd_1        | 	  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/reactor.py", line 77, in verify_installed_reactor
scrapyd_1        | 	    raise Exception(msg)
scrapyd_1        | 	Exception: The installed reactor (twisted.internet.epollreactor.EPollReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)
```

The twisted application runner logs the default reactor for the platform when it starts up so I think that we would need a way to load a reactor before calling run. However I am not a twisted expert and that is just my guess having stepped through the code.

```
scrapyd_1        | 2020-05-16T13:56:10+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 20.3.0 (/usr/bin/python3 3.6.9) starting up.
scrapyd_1        | 2020-05-16T13:56:10+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
```

### PR DESCRIPTION
**Pull request by pawelmhm**
This is because get_application launches default Twisted reactor when called from runner, and we want to respect reactor settings from Scrapy. I also think there is some weird circularity in current code.

Fixes #377

## How code in master branch works now

1. twisted Application is launched with some reactor settings, get_application() called once
2. server listens to requests
3. scrapyd-client sends deploy request, POST to addversion endpoint comes
4. webservice launches subprocess scrapyd.runner with argument list, to list Scrapy spiders
5. this subprocess calls get_application() 2nd time, this time without twistd specific settings, so even if you pass asyncioreactor to twistd, this won't be respected, and it will launch default Twisted reactor (epoll on Linux)
6. scrapy execute() is called, scrapy CrawlerProcess is trying to install reactor, but it realizes there is already default Twisted epoll reactor running, error is supressed
7. scrapy raises Exception when it tries to verify that reactor from settings is equal to reactor running, exception: The installed reactor (twisted.internet.epollreactor.EPollReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)

## To fix this:

on point 5) instead of calling get_application we just get Eggstorage, without application object. I think there is no need for an application object in runner which is called from Application already as subprocess. If root process is creating subprocess I do not expect it to create another object that manages root process. So now it won't call application

## TODO

- [x] unit tests
- [x] check if it doesn't break anything important

### CODE REVIEW

**Comment by pawelmhm** [comment]
fixes https://github.com/scrapy/scrapyd/issues/377

**Comment by pawelmhm** [comment]
waiting for this: https://github.com/scrapy/scrapyd/pull/412 to be merged, after that I'll add unit test here

**Comment by jpmckinney** [comment]
Sounds good to me. I've done a quick review of #412. Let me know if anything else you need.

**Comment by pawelmhm** [comment]
Windows tests for 3.8+ are hanging for some reason, I tested on local windows laptop, and it worked fine, not sure what is it in environment here. I don't know if it runs this test or if it is just hanging there before starting tests 

image

**Comment by pawelmhm** [comment]
removed windows, created issue for investigating this

**Comment by pawelmhm** [comment]
@jpmckinney so I'll integrate this PR with current master and merge. Then we can release 1.3 version, there is a lot of fresh code available. Next step in 2022 we can release 2.0 with this https://github.com/scrapy/scrapyd/pull/421.

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
> @jpmckinney so I'll integrate this PR with current master and merge. Then we can release 1.3 version, there is a lot of fresh code available. Next step in 2022 we can release 2.0 with this #421, possibly also this #304?

Sounds good to me!

**Pull request merged**
